
# rules

all:
	@for subdir in $(SUBDIRS); do\
		echo "make[1]: Entering directory \`$(PWD)/$$subdir"\';\
		PWD=$(PWD)/$$subdir;\
		if ! $(MAKE) --no-print-directory -C $(PWD)/$$subdir; then exit 1; fi;\
		echo "make[1]: Leaving directory \`$(PWD)/$$subdir"\';\
	done

install:
	@for subdir in $(SUBDIRS); do\
		echo "make[1]: Entering directory \`$(PWD)/$$subdir"\';\
		PWD=$(PWD)/$$subdir;\
		if ! $(MAKE) --no-print-directory -C $(PWD)/$$subdir install; then exit 1; fi;\
		echo "make[1]: Leaving directory \`$(PWD)/$$subdir"\';\
	done

clean:
	@for subdir in $(SUBDIRS); do\
		PWD=$(PWD)/$$subdir;\
		if ! $(MAKE) -C $(PWD)/$$subdir clean; then exit 1; fi;\
	done

deps:
	@for subdir in $(SUBDIRS); do\
		PWD=$(PWD)/$$subdir;\
		$(MAKE) -C $(PWD)/$$subdir deps;\
	done

